# Generated by Django 4.2.2 on 2023-07-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(db_column='idTipo', primary_key=True, serialize=False, verbose_name='ID_tipo_Usuario')),
                ('tipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vinilo',
            fields=[
                ('idVinilo', models.AutoField(db_column='idVinilo', primary_key=True, serialize=False, verbose_name='Id_Vinilo')),
                ('nombreArt', models.CharField(max_length=50)),
                ('nombreDisco', models.CharField(max_length=80)),
                ('valorDisco', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('appPaterno', models.CharField(max_length=30)),
                ('appMaterno', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('activo', models.IntegerField()),
                ('tipoUsuario', models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.CASCADE, to='newProject.tipousuario')),
            ],
        ),
    ]
