# Generated by Django 4.2.2 on 2023-06-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(db_column='idTipo', primary_key=True, serialize=False, verbose_name='Id_Tipo_Usuario')),
                ('tipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vinilo',
            fields=[
                ('idVinilo', models.AutoField(db_column='idVinilo', primary_key=True, serialize=False, verbose_name='Id_Vinilo')),
                ('nombreArt', models.CharField(max_length=50)),
                ('nombreDisco', models.CharField(max_length=80)),
                ('valorDisco', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apaterno', models.CharField(max_length=60)),
                ('amaterno', models.CharField(max_length=60)),
                ('fechaNac', models.DateField()),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('tipoUsuario', models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.CASCADE, to='newProject.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='tracksVinilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTrack', models.IntegerField(db_column='numTrack', verbose_name='Numero_Track')),
                ('nombreTrack', models.CharField(max_length=60)),
                ('idVinilo', models.ForeignKey(db_column='idVinilo', on_delete=django.db.models.deletion.CASCADE, to='newProject.vinilo')),
            ],
        ),
        migrations.CreateModel(
            name='descVinilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sello', models.CharField(max_length=60)),
                ('anno_lto', models.DateField()),
                ('pais', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=100)),
                ('idVinilo', models.ForeignKey(db_column='idVinilo', on_delete=django.db.models.deletion.CASCADE, to='newProject.vinilo')),
            ],
        ),
    ]
