# Generated by Django 4.2.2 on 2023-07-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fechaNac',
            new_name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='amaterno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apaterno',
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='appMaterno',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='appPaterno',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='idTipoUsuario',
            field=models.AutoField(db_column='idTipo', primary_key=True, serialize=False, verbose_name='ID_tipo_Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
