# Generated by Django 4.2.2 on 2023-07-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinilo',
            name='idVinilo',
            field=models.IntegerField(db_column='idVinilo', primary_key=True, serialize=False, verbose_name='Id_Vinilo'),
        ),
    ]
